version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    restart: always
    ports:
      - "6378:6379"
#
#  app:
#    build:
#      context: .
#      dockerfile: dockerfile
#    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#    environment:
#      - DATABASE_URL=postgresql+asyncpg://foo:foo@db:5432/foodb
#      - REDIS_URL=redis://redis:6379/0
#    depends_on:
#      - db
#      - redis

volumes:
  db_data:
