# Generated by Django 5.2.3 on 2025-06-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleCSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, max_length=255, null=True)),
                ('col2', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
