# syntax=docker/dockerfile:1
FROM python:3.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y build-essential libpq-dev gcc postgresql-client curl && rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

COPY pyproject.toml README.md ./
COPY uv.lock ./
RUN uv sync --frozen

COPY . .

ENV PATH="/app/.venv/bin:${PATH}"

RUN chmod +x entrypoint.sh
CMD ["./entrypoint.sh"]
